/* soapagentService.h
   Generated by gSOAP 2.8.98 for soapAgentServer.hpp

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapagentService_H
#define soapagentService_H
#include "soapH.h"

    class SOAP_CMAC agentService {
      public:
        /// Context to manage service IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this service and should be deleted by the destructor
        bool soap_own;
        /// Variables globally declared in soapAgentServer.hpp, if any
        /// Construct a service with new managing context
        agentService();
        /// Copy constructor
        agentService(const agentService&);
        /// Construct service given a shared managing context
        agentService(struct soap*);
        /// Constructor taking input+output mode flags for the new managing context
        agentService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        agentService(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~agentService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void agentService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual agentService *copy() SOAP_PURE_VIRTUAL_COPY;
        /// Copy assignment
        agentService& operator=(const agentService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
    #ifndef WITH_NOIO
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port, int backlog = 1);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port, int backlog = 1);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET upon error)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET upon error)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
    #endif
        /// After accept() serve the pending request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a pending request (returns SOAP_OK or error code)
        virtual int dispatch();
        virtual int dispatch(struct soap *soap);
        //
        // Service operations are listed below: you should define these
        // Note: compile with -DWITH_PURE_VIRTUAL to declare pure virtual methods
        //
        /// Web service operation 'get-cpu-info' implementation, should return SOAP_OK or error code
        virtual int get_cpu_info(std::string &info) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-cpu-usage' implementation, should return SOAP_OK or error code
        virtual int get_cpu_usage(float &usage) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-memory-info' implementation, should return SOAP_OK or error code
        virtual int get_memory_info(std::string &info) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-memory-available' implementation, should return SOAP_OK or error code
        virtual int get_memory_available(int &available) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-memory-free' implementation, should return SOAP_OK or error code
        virtual int get_memory_free(int &free) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-drive-number' implementation, should return SOAP_OK or error code
        virtual int get_drive_number(unsigned int &number) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-drive-names' implementation, should return SOAP_OK or error code
        virtual int get_drive_names(std::string *names) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-drive-info' implementation, should return SOAP_OK or error code
        virtual int get_drive_info(const std::string& name, std::string &info) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-drive-total-capacity' implementation, should return SOAP_OK or error code
        virtual int get_drive_total_capacity(const std::string& name, float &total) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-drive-used-capatity' implementation, should return SOAP_OK or error code
        virtual int get_drive_used_capatity(const std::string& name, float &usage) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-interface-number' implementation, should return SOAP_OK or error code
        virtual int get_interface_number(unsigned int &number) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-interface-names' implementation, should return SOAP_OK or error code
        virtual int get_interface_names(std::string *names) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-interface-info' implementation, should return SOAP_OK or error code
        virtual int get_interface_info(const std::string& name, std::string &info) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-interface-ip-address' implementation, should return SOAP_OK or error code
        virtual int get_interface_ip_address(const std::string& name, std::string &ip_address) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'get-interface-speed' implementation, should return SOAP_OK or error code
        virtual int get_interface_speed(const std::string& name, int &speed) SOAP_PURE_VIRTUAL;
        //
        /// Web service one-way operation 'set-hostname' implementation, should return value of send_set-hostname_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message
        virtual int set_hostname(const std::string& hostname) SOAP_PURE_VIRTUAL;
        /// Web service asynchronous send of HTTP Accept acknowledgment to be called in 'set-hostname', returns SOAP_OK or error code
        virtual int send_set_hostname_empty_response(int soap_http_status = 202) { return soap_send_empty_response(this->soap, soap_http_status); }
        //
        /// Web service one-way operation 'set-interface-ip-address' implementation, should return value of send_set-interface-ip-address_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message
        virtual int set_interface_ip_address(const std::string& name, const std::string& ip_address, const std::string& subnet_mask) SOAP_PURE_VIRTUAL;
        /// Web service asynchronous send of HTTP Accept acknowledgment to be called in 'set-interface-ip-address', returns SOAP_OK or error code
        virtual int send_set_interface_ip_address_empty_response(int soap_http_status = 202) { return soap_send_empty_response(this->soap, soap_http_status); }
    };
#endif
